version: 2.1
orbs:
  docker: circleci/docker@0.5.20
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: sparkgeo/notebooks-manual-task
          tag: latest
          path: ./base-image/