name: Docker Image CI

on: [push]

env:
  docker_repo: sparkgeo
  image_name: notebooks-manual-task
  image_tag: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./base-image --file base-image/Dockerfile --tag ${{ env.docker_repo }}/${{ env.image_name }}:${{ env.image_tag }}
    - name: Dockerhub login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    - name: Push image
      run: docker push ${{ env.docker_repo }}/${{ env.image_name }}:${{ env.image_tag }}
      
